---
  - name: installing GO packages
    package:
      pkg: "{{ go_packages }}"
      update_cache: yes
    tags: ["dev", "packages"]

  - name: Copy GO files
    copy:
      src: ../source/go/
      dest: "{{go_project_path}}"
      mode: preserve
    tags: ["dev", "go", "copy"]

  - name: Run GO webserver
    shell: |
      GOPATH={{go_project_path}}
      cd {{go_project_path}}
      go build {{go_project_name}}.go
      kill -9 $(pidof {{go_project_name}})
      #rm -f {{go_project_name}}
      nohup {{go_project_path}}/{{go_project_name}} &
    tags: ["dev", "go", "runapp"]

  - name: iptables 8000
    iptables:
      chain: INPUT
      protocol: tcp
      destination_port: "{{ go_project_port }}"
      jump: ACCEPT
    notify: save iptables
    tags: ["dev", "go", "iptables"]