---
  - name: include GO app deploy
    include: go-bin.yml
    tags: ["dev", "go"]

  - name: iptables allow ping
    iptables:
      chain: INPUT
      protocol: icmp
      icmp_type: echo-request
      jump: ACCEPT
    notify: save iptables
    tags: ["dev", "icmp", "iptables"]

  - name: iptables allow ping reply
    iptables:
      chain: OUTPUT
      protocol: icmp
      icmp_type: echo-reply
      jump: ACCEPT
    notify: save iptables
    tags: ["dev", "icmp", "iptables"]