---
  - name: installing Python packages
    package:
      pkg: "{{ go_packages }}"
      update_cache: yes
    tags: ["dev", "python", "packages"]

  - name: Copy Python files
    copy:
      src: ../Python/
      dest: /project/python
      mode: preserve
    tags: ["dev", "python", "python_copy"]

  - name: Run Python webserver
    shell: |
      cd /project/python/

      python3.5 -m venv webapp_venv
      source webapp_venv/bin/activate

      pip install --upgrade pip
      pip install gunicorn

      pkill gunicorn
      gunicorn -b 0.0.0.0:8001 py-webapp --name my_python_websrv --access-logfile gcorn.log --workers=1 &
      #nohup python3 /project/python/websrv.py &
    tags: ["dev", "python", "python_run"]

  - name: iptables 8001
    iptables:
      chain: INPUT
      protocol: tcp
      destination_port: 8001
      jump: ACCEPT
    notify: save iptables
    tags: ["dev", "python", "iptables"]
