---
  - name: Add PostgreSQL official APT repository
    apt_repository:
      repo: "deb http://apt.postgresql.org/pub/repos/apt/ {{ansible_distribution_release}}-pgdg main"
      # repo: "deb http://apt.postgresql.org/pub/repos/apt/ xenial-pgdg main" #deb http://apt.postgresql.org/pub/repos/apt/ bionic-pgdg main
      state: present
    tags: ["repo", "postgres_deploy"]

  - name: Adding APT repository key
    become: yes
    apt_key:
      id: ACCC4CF8
      url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
    tags: ["repo", "postgres_deploy"]

  - name: Install Postgresql
    package:
      pkg: "{{ item }}"
      update_cache: yes
      state: latest
    with_items:
      - libpq-dev
      - python-psycopg2
      - postgresql-{{postgresql_version}}
    tags: ["packages", "postgres_deploy"]

  - name: Copy DB config
    copy:
      src: ../source/db/pg_hba.conf
      dest: /etc/postgresql/10/main/pg_hba.conf
    tags: ["postgres_deploy"]

#  - name: Set postgres user password
#    postgresql_user:
#      user: postgres
#      password: "QWErty123"
#    tags: ["postgres_deploy"]

  - name: Restart PostgreSQL service
    service:
      name: postgresql
      state: restarted
    tags: ["postgres_deploy"]

  - name: Copy DB dump
    copy:
      src: ../source/db/
      dest: /opt/ubershop/bd_dump/
    tags: ["postgres_deploy"]

  - name: Drop database with name "ubershop"
    postgresql_db:
      name: ubershop
      state: absent
    tags: ["postgres_deploy", "create_db"]

  - name: Create a new database with name "ubershop"
    postgresql_db:
      name: ubershop
      state: present
    tags: ["postgres_deploy", "create_db"]

  - name: Restore BD from file
    postgresql_db:
      name: ubershop
      state: restore
      target: /opt/ubershop/bd_dump/ub.dump
      #target_opts: "-Fc"
      #login_user: "postgres"
      #login_password: "QWErty123"
    notify: Restart postgress
    tags: ["postgres_deploy", "postgres_restore"]

  - name: Connect to database, create api user, and grant access
    postgresql_user:
      db: ubershop
      name: api
      password: QWErty123
      #priv: "CONNECT/products:ALL"
      role_attr_flags: CREATEDB
    notify: Restart postgress
    tags: ["postgres_deploy"]